require('mini.starter').setup()
require('mini.comment').setup()
require('mini.pairs').setup()
require('mini.tabline').setup()
require('mini.trailspace').setup()
require('mini.jump').setup({delay = { highlight = 80 }})
